infra:
  env: dev

image:
  repo: "ronincloud.azurecr.io/infx-api"
  tag: "1.0.0"
  pullPolicy: Always

deployment:
  replicas: 3

resources:
  requests:
    cpu: .5
    memory: 256Mi
  limits:
    memory: 1Gi

disruption:
  minAvailable: 2

database:
  name: "clinical-content"
  host: ""
  user: "infx-api_user"