codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
       # this is the advanced section
        branches: null
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: true
    patch:
      default:
        # basic
        target: 80
        threshold: 1%
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
