version: "3.8"

services:
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './app:/app/app:z'
    command:
      - "python"
      - "-m"
      - "app"
      - "--reload"
    ports:
      - 8000:8000
    environment:
      - APP_NAME=infx_content
      - PYTHONUNBUFFERED=0
       - SECRET_KEY=change_me_in_prod
