version: "3.8"

services:
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - './app:/app/app:z'
    command:
      - "python"
      - "-m"
      - "app"
      - "--reload"
    ports:
      - 8000:8000
