apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "hashi.fullname" . }}-config
data:
  K8S_ENV: "{{ .Values.infra.env }}"
  ROLLBAR_ENDPOINT: "http://rollbar.com"
  DATABASE_HOST: "{{ .Values.database.host}}"
  DATABASE_USER: "{{ .Values.database.user}}"
  DD_SERVICE: "{{ include "hashi.fullname" . }}"