infra:
  env: prod

database:
  name: "clinical-content"
  host: "psql-clinical-content-prod-centralus.postgres.database.azure.com"
  user: "hashi_user"

elasticsearch:
  host: 80587c9d816a47d0838b3e262008b9ee.privatelink.centralus.azure.elastic-cloud.com:9243
  user: elastic
