infra:
  env: dev

image:
  repo: "ronincloud.azurecr.io/hashi"
  tag: "1.0.0"
  pullPolicy: Always

deployment:
  replicas: 3

resources:
  requests:
    cpu: .5
    memory: 128Mi
  limits:
    memory: 128Mi

disruption:
  minAvailable: 2
